// nss-app-dashboard/src/components/EventCard.tsx
'use client'

import Image from 'next/image'

interface EventCardProps {
  title: string
  date: string
  description: string
  category: string
  hours: string
  participants: Array<{
    avatar: string
    alt: string
  }>
  participantCount: number
  onEdit: () => void
  onViewParticipants: () => void
  onDelete: () => void
}

export function EventCard({ 
  title, 
  date, 
  description, 
  category, 
  hours, 
  participants, 
  participantCount,
  onEdit,
  onViewParticipants,
  onDelete
}: EventCardProps) {
  const getCategoryColor = (category: string) => {
    switch (category.toLowerCase()) {
      case 'area based - 1':
        return 'bg-blue-500'
      case 'college event':
        return 'bg-purple-500'
      case 'camp':
        return 'bg-orange-500'
      case 'workshop':
        return 'bg-indigo-500'
      default:
        return 'bg-gray-500'
    }
  }

  return (
    <div className="card-glass hover-lift rounded-xl flex flex-col transition-all duration-300 ease-out px-4 py-3.5 md:px-3.5 md:py-3 lg:px-4 lg:py-2.4">
      <div className="flex-grow">
        <div className="flex justify-between items-start mb-3 md:mb-2">
          <h3 
            className="font-semibold text-gray-100 truncate pr-2 text-base md:text-sm lg:text-base" 
            title={title}
          >
            {title}
          </h3>
          <span className="text-sm md:text-xs text-gray-400 whitespace-nowrap">{date}</span>
        </div>
        <p className="text-sm md:text-xs text-gray-400 mb-4 md:mb-3 leading-relaxed line-clamp-3 md:line-clamp-2">
          {description}
        </p>
        <div className="flex flex-wrap items-center mb-4 md:mb-3 gap-1">
          <span className="tag text-xs">
            <span className={`tag-dot ${getCategoryColor(category)}`}></span>
            {category}
          </span>
          <span className="tag text-xs">
            <span className="tag-dot bg-green-500"></span>
            {hours} Hrs
          </span>
        </div>
      </div>
      <div className="flex items-center justify-between pt-3 border-t border-gray-700/20 mt-auto">
        <div className="flex items-center -space-x-2">
          {participants.map((participant, index) => (
            <Image 
              key={index}
              src={participant.avatar} 
              alt={participant.alt} 
              className="w-6 h-6 md:w-5 md:h-5 rounded-full border-2 border-gray-700/50"
              width={24}
              height={24}
            />
          ))}
          <span className="text-sm md:text-xs text-gray-500 pl-3">+{participantCount}</span>
        </div>
        <div className="flex space-x-3 md:space-x-1.5">
          <button 
            title="Edit" 
            className="pwa-button action-button text-gray-400 hover:text-blue-400 p-2 md:p-1.5 rounded-lg text-sm md:text-xs focus-visible"
            onClick={onEdit}
          >
            <i className="fas fa-pencil-alt"></i>
          </button>
          <button 
            title="Participants" 
            className="pwa-button action-button text-gray-400 hover:text-green-400 p-2 md:p-1.5 rounded-lg text-sm md:text-xs focus-visible"
            onClick={onViewParticipants}
          >
            <i className="fas fa-users"></i>
          </button>
          <button 
            title="Delete" 
            className="pwa-button action-button text-gray-400 hover:text-red-500 p-2 md:p-1.5 rounded-lg text-sm md:text-xs focus-visible"
            onClick={onDelete}
          >
            <i className="fas fa-trash-alt"></i>
          </button>
        </div>
      </div>
    </div>
  )
}

// nss-app-dashboard/components/EventCard.vue
<template>
  <div 
    class="card-glass hover-lift rounded-xl flex flex-col transition-all duration-300 ease-out" 
    style="padding: 0.85rem;"
  >
    <div class="flex-grow">
      <div class="flex justify-between items-start mb-2">
        <h3 
          class="font-semibold text-gray-100 truncate pr-2" 
          style="font-size: 0.94rem;" 
          :title="event.title"
        >
          {{ event.title }}
        </h3>
        <span class="text-xs text-gray-400 whitespace-nowrap">{{ formatDate(event.date) }}</span>
      </div>
      
      <p class="text-xs text-gray-400 mb-3 leading-relaxed line-clamp-2">
        {{ event.description }}
      </p>
      
      <div class="flex flex-wrap items-center mb-3">
        <span class="tag">
          <span class="tag-dot" :class="getCategoryColor(event.category)"></span>
          {{ event.category }}
        </span>
        <span class="tag">
          <span class="tag-dot bg-green-500"></span>
          {{ event.hours }} {{ event.hours === 1 ? 'Hr' : 'Hrs' }}
        </span>
      </div>
    </div>
    
    <div class="flex items-center justify-between pt-3 border-t border-gray-700/20 mt-auto">
      <div class="flex items-center -space-x-2">
        <img 
          v-for="(participant, index) in event.participants.slice(0, 3)" 
          :key="index"
          :src="participant.avatar" 
          :alt="participant.name" 
          class="w-5 h-5 rounded-full border-2 border-gray-700/50"
        >
        <span class="text-xs text-gray-500 pl-3">
          +{{ event.participants.length - 3 > 0 ? event.participants.length - 3 : event.participants.length }}
        </span>
      </div>
      
      <div class="flex space-x-1">
        <button 
          title="Edit" 
          class="action-button text-gray-400 hover:text-blue-400 p-1.5 rounded-lg text-xs"
          @click="$emit('edit', event)"
        >
          <i class="fas fa-pencil-alt"></i>
        </button>
        <button 
          title="Participants" 
          class="action-button text-gray-400 hover:text-green-400 p-1.5 rounded-lg text-xs"
          @click="$emit('view-participants', event)"
        >
          <i class="fas fa-users"></i>
        </button>
        <button 
          title="Delete" 
          class="action-button text-gray-400 hover:text-red-500 p-1.5 rounded-lg text-xs"
          @click="$emit('delete', event)"
        >
          <i class="fas fa-trash-alt"></i>
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
defineProps({
  event: {
    type: Object,
    required: true
  }
})

defineEmits(['edit', 'view-participants', 'delete'])

const formatDate = (date) => {
  const d = new Date(date)
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })
}

const getCategoryColor = (category) => {
  const colors = {
    'Area Based - 1': 'bg-blue-500',
    'Area Based - 2': 'bg-cyan-500',
    'College Event': 'bg-purple-500',
    'University Event': 'bg-pink-500',
    'Camp': 'bg-orange-500',
    'Workshop': 'bg-indigo-500',
    'Competition': 'bg-yellow-500',
    'Other': 'bg-gray-500'
  }
  return colors[category] || 'bg-gray-500'
}
</script>

<style scoped>
.line-clamp-2 {
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}
</style>
